GOENV: DEV
SRV_EXAMPLE__Log_Level: debug
SRV_EXAMPLE__Log_Output: Always
SRV_EXAMPLE__Server_Debug: "true"
SRV_EXAMPLE__Server_Port: 8080
SRV_EXAMPLE__ClientID_Endpoint: https://srv-id.base.d.rktl.work
SRV_EXAMPLE__Postgres_Endpoint: postgresql://dbuser:2001@localhost:5432/mydb?sslmode=disable
